language: python
python:
   - "3.6"
   - "3.7"
   - "3.8"
   - "3.9"
   - "3.9-dev"
git:
   depth: false
install:
   - pip install -r requirements-test.txt
   - pip install pytest-cov
   - pip install -e .
script:
   - pytest --cov-report=xml --cov-branch --cov=modypy
after_success:
   - bash <(curl -s https://codecov.io/bash)
