import math

from simtree.blocks.linear import LTISystem

"""
A collection fo electro-mechanical blocks.
"""


class DCMotor(LTISystem):
    """
    A DC motor with external load.

    This model has
        - two inputs, representing the input voltage U(t) and the torque of
          the external load tau_l(t),
        - two states, representing the speed omega(t) (in rad/[T]) of the motor
          and the current i(t) (in [I]) flowing through the coil, and
        - two outputs, representing the speed n(t) (in 1/[T]) of the motor,
          the current i(t) and the torque tau(t) generated by the motor.

    The parameters are
        - Kv, the motor constant in [ML^2/(IT^2)] (usually Vs/rad),
        - R, the internal resistance of the coil [ML^2/(I^2T^3)] (usually Ohm),
        - L, the inductance of the coil [ML^2/(I^2T^2)] (usually Henry), and
        - J, the moment of inertia of the rotor [ML^2] (usually kg*m^2).

    The model expresses the following equations of motion:

        - electrical: U(t) = Kv*omega(t) + R*i(t) + L*di(t)/dt
        - mechanical: Kv*I(t) = J*domega(t)/dt + tau_l(t)

    The outputs are given as follows:

        - speed: n(t) = omega(t)/(2*pi)
        - current: i(t)
        - torque: Kv*i(t)
    """
    def __init__(self, Kv, R, L, J, **kwargs):
        LTISystem.__init__(self,
                           A=[[0, Kv / J],
                              [-Kv / L, -R / L]],
                           B=[[0, -1 / J],
                              [1 / L, 0]],
                           C=[[1 / (2 * math.pi), 0],
                              [0, 1],
                              [0, Kv]],
                           D=[[0, 0],
                              [0, 0],
                              [0, 0]],
                           feedthrough_inputs=[],
                           **kwargs)
