name: Python Tests

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v1
        with:
          # We need submodules for the documentation styles
          submodules: true
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install depedencies
        run : |
          pip install -r requirements-test.txt -r requirements-docs.txt
      - name: Install MoDyPy properly for installation testing
        run : |
          pip install .
      - name: Test proper installation
        run : |
          pytest
      - name: Test HTML documentation build
        run : |
          python -m sphinx -b html docs docs/_build/html
      - name: Install MoDyPy locally for coverage testing
        run : |
          pip install -e .
      - name: Test for coverage
        run : |
          pytest --cov=modypy --cov-config=.coveragerc --cov-report=xml
      - name: Show coverage report
        run : |
          cat coverage.xml
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          name: Python ${{ matrix.python_version }}
